// 0.9.3 — Diary Calendar / health events
let diaryMode = "progress";
let diaryCalendarMonth = getTodayKey().slice(0, 7);
function setDiaryMode(mode){ diaryMode = mode === "calendar" ? "calendar" : "progress"; openHistory(); }
function createDiaryModeSwitcher(){ return `<div class="diary-mode-switcher" role="tablist"><button class="diary-mode-button ${diaryMode === "progress" ? "active" : ""}" onclick="setDiaryMode('progress')">Прогресс</button><button class="diary-mode-button ${diaryMode === "calendar" ? "active" : ""}" onclick="setDiaryMode('calendar')">Календарь</button></div>`; }
function getHealthEventTypes(){ return [{id:"vaccination",name:"Вакцинация",emoji:"💉"},{id:"endo",name:"Эндопаразиты",emoji:"🪱"},{id:"ecto",name:"Эктопаразиты",emoji:"🦟"},{id:"dental_cleaning",name:"Ультразвуковая чистка зубов под наркозом",emoji:"🦷"},{id:"medicine",name:"Лечение / лекарство",emoji:"💊"},{id:"other",name:"Другое",emoji:"🩺"}]; }
function getHealthEvents(catId){ return typeof getCatHealth === "function" ? (getCatHealth(catId).medicalEvents || []) : []; }
function saveHealthEvents(catId,events){ if(typeof getCatHealth !== "function" || typeof saveCatHealth !== "function") return; const profile=getCatHealth(catId); profile.medicalEvents=events; saveCatHealth(catId,profile); }
function getDiaryCalendarCat(){ const cats=getCats(); if(!cats.length)return null; return diarySelectedCatId && diarySelectedCatId!=="all" ? (cats.find(c=>c.id===diarySelectedCatId)||getActiveCat()) : getActiveCat(); }
function shiftDiaryMonth(key,delta){ const [y,m]=key.split("-").map(Number),d=new Date(y,m-1+delta,1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`; }
function formatDiaryMonth(key){ const [y,m]=key.split("-").map(Number); return new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(new Date(y,m-1,1)); }
function getEventEmoji(event){ return event.emoji || getHealthEventTypes().find(t=>t.id===event.type)?.emoji || "🩺"; }
function renderDiaryCalendar(){ const cat=getDiaryCalendarCat(); if(!cat)return `<div class="card history-empty">🐾<h2>Добавьте кошку</h2></div>`; const [y,m]=diaryCalendarMonth.split("-").map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),offset=(first.getDay()+6)%7,today=getTodayKey(),events=getHealthEvents(cat.id),cells=[]; for(let i=0;i<offset;i++)cells.push(`<div class="diary-calendar-day empty"></div>`); for(let day=1;day<=days;day++){const date=`${diaryCalendarMonth}-${String(day).padStart(2,"0")}`,ev=events.filter(e=>e.date===date||e.nextDate===date),emojis=[...new Set(ev.map(getEventEmoji))];cells.push(`<button class="diary-calendar-day ${date===today?"today":""} ${ev.length?"has-events":""}" onclick="openDiaryCalendarDay('${date}')"><span>${day}</span>${emojis.length?`<small>${emojis.join("")}</small>`:""}</button>`);} return `<div class="diary-calendar-card card"><div class="diary-calendar-header"><button onclick="changeDiaryCalendarMonth(-1)">‹</button><strong>${escapeHtml(formatDiaryMonth(diaryCalendarMonth))}</strong><button onclick="changeDiaryCalendarMonth(1)">›</button></div><div class="diary-calendar-weekdays"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span>Сб</span><span>Вс</span></div><div class="diary-calendar-grid">${cells.join("")}</div></div><div id="diaryCalendarDayEvents"></div><button class="button diary-add-health" onclick="openDiaryHealthEventForm()">＋ Добавить событие</button>`; }
function changeDiaryCalendarMonth(delta){ diaryCalendarMonth=shiftDiaryMonth(diaryCalendarMonth,delta); openHistory(); }
function openDiaryCalendarDay(date){ const cat=getDiaryCalendarCat(); if(!cat)return; const ev=getHealthEvents(cat.id).filter(e=>e.date===date||e.nextDate===date),target=document.getElementById("diaryCalendarDayEvents"); if(!target)return; target.innerHTML=`<div class="section-title">${escapeHtml(new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${date}T12:00:00`)))}</div>${ev.length?ev.map(e=>{const title=e.title||getHealthEventTypes().find(x=>x.id===e.type)?.name||"Событие";return `<div class="card health-event-card" onclick='openDiaryHealthEventForm(${JSON.stringify(e)})'><div><strong>${getEventEmoji(e)} ${escapeHtml(title)}</strong>${e.note?`<div class="health-event-note">${escapeHtml(e.note)}</div>`:""}</div><div>${e.nextDate?`<small>Следующая: ${formatShortDate(e.nextDate)}</small>`:""}${e.reminderDays?`<small>Напомнить за ${e.reminderDays} дн.</small>`:""}</div></div>`;}).join(""):"<div class=\"card health-empty\">На этот день событий нет.</div>"}`; }
function formatShortDate(d){ if(!d)return""; const [y,m,day]=d.split("-"); return `${day}.${m}.${y}`; }
function openDiaryHealthEventForm(existing=null){ const cat=getDiaryCalendarCat(); if(!cat)return; const types=getHealthEventTypes(),cur=existing||{},type=types.find(t=>t.id===cur.type)||types[0],modal=document.createElement("div"); modal.className="health-event-modal"; modal.innerHTML=`<div class="health-event-overlay" onclick="this.parentElement.remove()"></div><div class="health-event-dialog"><button class="health-event-close" onclick="this.closest('.health-event-modal').remove()">×</button><h2>${existing?"Событие здоровья":"Новое событие"}</h2><form onsubmit="saveDiaryHealthEvent(event,'${cur.id||""}')"><label class="form-label">Событие<select id="diaryHealthType" class="input">${types.map(t=>`<option value="${t.id}" ${t.id===type.id?"selected":""}>${t.emoji} ${t.name}</option>`).join("")}</select></label><label class="form-label">Эмодзи<input id="diaryHealthEmoji" class="input" maxlength="2" value="${escapeHtml(cur.emoji||type.emoji)}"></label><label class="form-label">Дата события<input id="diaryHealthDate" class="input" type="date" required value="${cur.date||getTodayKey()}"></label><label class="form-label">Следующая дата<input id="diaryHealthNextDate" class="input" type="date" value="${cur.nextDate||""}"></label><label class="form-label">Напомнить заранее<select id="diaryHealthReminder" class="input">${[1,3,7,14,30].map(d=>`<option value="${d}" ${Number(cur.reminderDays||14)===d?"selected":""}>За ${d} ${d===1?"день":"дней"}</option>`).join("")}</select></label><label class="form-label">Заметка<textarea id="diaryHealthNote" class="input" rows="3">${escapeHtml(cur.note||"")}</textarea></label><button class="button" type="submit">Сохранить</button></form></div>`; document.body.appendChild(modal); }
function saveDiaryHealthEvent(e,id){ e.preventDefault(); const cat=getDiaryCalendarCat(); if(!cat)return; const typeId=document.getElementById("diaryHealthType").value,type=getHealthEventTypes().find(t=>t.id===typeId),item={id:id||`health_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,type:typeId,title:type.name,emoji:document.getElementById("diaryHealthEmoji").value||type.emoji,date:document.getElementById("diaryHealthDate").value,nextDate:document.getElementById("diaryHealthNextDate").value||"",reminderDays:Number(document.getElementById("diaryHealthReminder").value||14),note:document.getElementById("diaryHealthNote").value.trim()}; const events=getHealthEvents(cat.id),i=events.findIndex(x=>x.id===item.id); if(i>=0)events[i]=item;else events.push(item); saveHealthEvents(cat.id,events); document.querySelector(".health-event-modal")?.remove(); diaryCalendarMonth=item.date.slice(0,7); openHistory(); }
